-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK AS b
JOIN AUTHOR AS a
ON b.AUTHOR_ID = a.AUTHOR_ID 
JOIN BOOK_SALES AS s
ON b.BOOK_ID = s.BOOK_ID 
WHERE s.SALES_DATE >= '2022-01-01'
  AND s.SALES_DATE <  '2022-02-01' 
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;