-- 코드를 입력하세요
SELECT PRODUCT_CODE, (SUM(SALES_AMOUNT) * p.PRICE) AS SALES
FROM PRODUCT AS p
JOIN OFFLINE_SALE AS o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;