-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, 
    ROUND(c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS p
ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND p.DURATION_TYPE = '30일 이상'
  AND c.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
  )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_ID DESC;