-- 코드를 입력하세요
SELECT i.FOOD_TYPE, i.REST_ID, i.REST_NAME, i.FAVORITES AS FAVORITES
FROM REST_INFO as i
JOIN (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) as f
ON i.FOOD_TYPE = f.FOOD_TYPE AND i.FAVORITES = f.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;
