-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, o.SUM_AMOUNT * p.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT as p
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT
     FROM FOOD_ORDER
     WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
     GROUP BY PRODUCT_ID) AS o
ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID;