-- 코드를 입력하세요
SELECT
    h.HISTORY_ID,
    FLOOR(c.DAILY_FEE * h.days * (100 - COALESCE(p.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM (
  SELECT 
    HISTORY_ID,
    CAR_ID,
    DATEDIFF(END_DATE, START_DATE) + 1 AS days
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS h
JOIN (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
) AS c
ON h.CAR_ID = c.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS p
  ON p.CAR_TYPE = c.CAR_TYPE
 AND (
      (p.DURATION_TYPE = '90일 이상' AND h.days >= 90)
   OR (p.DURATION_TYPE = '30일 이상' AND h.days >= 30 AND h.days < 90)
   OR (p.DURATION_TYPE = '7일 이상'  AND h.days >= 7  AND h.days < 30)
)
ORDER BY FEE DESC, h.HISTORY_ID DESC;