-- 코드를 작성해주세요
SELECT 
  d.ID,
  d.EMAIL,
  d.FIRST_NAME,
  d.LAST_NAME
FROM DEVELOPERS AS d
JOIN SKILLCODES AS s
  ON (d.SKILL_CODE & s.CODE) = s.CODE
WHERE s.CATEGORY = 'Front End'
GROUP BY d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
ORDER BY d.ID ASC;