-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, b.SUM_PRICE AS TOTAL_SALES
FROM USED_GOODS_USER AS u
JOIN (SELECT WRITER_ID, SUM(PRICE) AS SUM_PRICE
    FROM USED_GOODS_BOARD 
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID 
    HAVING SUM(PRICE) >= 700000) AS b
ON u.USER_ID = b.WRITER_ID
ORDER BY b.SUM_PRICE;