-- 코드를 입력하세요
SELECT mp.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS r
JOIN (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
            SELECT MAX(cnt)
            FROM (SELECT COUNT(*) AS cnt
                FROM REST_REVIEW
                GROUP BY MEMBER_ID) t
    )
) AS mr
JOIN MEMBER_PROFILE AS mp
ON r.MEMBER_ID = mr.MEMBER_ID AND r.MEMBER_ID = mp.MEMBER_ID
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT;
