-- 코드를 작성해주세요
WITH PYTHON AS (
    SELECT CODE AS PC
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
CS AS (
    SELECT CODE AS CSC
    FROM SKILLCODES
    WHERE NAME = 'C#'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
JOIN PYTHON JOIN CS
WHERE (SKILL_CODE & PC) != 0
   OR (SKILL_CODE & CSC) != 0
ORDER BY ID;