-- 코드를 작성해주세요
SELECT m.YEAR AS YEAR, (m.MAX_SIZE - d.SIZE_OF_COLONY) AS YEAR_DEV, d.ID
FROM ECOLI_DATA AS d
JOIN (
  SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS m
ON YEAR(d.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;