-- 코드를 입력하세요
SELECT DISTINCT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
JOIN (SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_CAR
     WHERE CAR_TYPE = '세단') AS c
ON h.CAR_ID = c.CAR_ID
WHERE START_DATE >= '2022-10-01' AND START_DATE < '2022-11-01'
ORDER BY h.CAR_ID DESC;