-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN (SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE MONTH(START_DATE) = 10
) AS h 
ON c.CAR_ID = h.CAR_ID
WHERE CAR_TYPE LIKE '%세단%'
ORDER BY c.CAR_ID DESC;