-- 코드를 작성해주세요
SELECT
  f.ID,
  n.FISH_NAME,
  f.LENGTH
FROM FISH_INFO AS f
JOIN (
  SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
  FROM FISH_INFO
  GROUP BY FISH_TYPE
) AS m
  ON f.FISH_TYPE = m.FISH_TYPE
 AND f.LENGTH = m.MAX_LEN
JOIN FISH_NAME_INFO AS n
  ON n.FISH_TYPE = f.FISH_TYPE
ORDER BY f.ID ASC;