-- 코드를 작성해주세요
SELECT i.ID, n.FISH_NAME, MAX(i.LENGTH) AS LENGTH
FROM FISH_INFO AS i
JOIN (
    SELECT ID, FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS f
ON i.FISH_TYPE = f.FISH_TYPE
    AND i.LENGTH = f.LENGTH
JOIN FISH_NAME_INFO AS n
ON i.FISH_TYPE = n.FISH_TYPE
GROUP BY i.FISH_TYPE
ORDER BY i.ID;