-- 코드를 작성해주세요
SELECT g.SCORE AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES AS e
JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
      FROM HR_GRADE
      GROUP BY EMP_NO
      ORDER BY SCORE DESC
      LIMIT 1
) AS g
ON e.EMP_NO = g.EMP_NO;