-- 코드를 입력하세요
SELECT p.CATEGORY, p.PRICE AS MAX_PRICE, p.PRODUCT_NAME
FROM FOOD_PRODUCT as p
JOIN (
    SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS m
ON p.CATEGORY = m.CATEGORY AND p.PRICE = m.MAX_PRICE
WHERE p.CATEGORY IN('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;