-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, MAX(i.LENGTH) AS MAX_LENGTH, i.FISH_TYPE
FROM FISH_INFO AS i
JOIN (
    SELECT FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS FISTH_LENGTH_AVG
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING FISTH_LENGTH_AVG >= 33) AS a
ON i.FISH_TYPE = a.FISH_TYPE
GROUP BY i.FISH_TYPE
ORDER BY i.FISH_TYPE;